version: '2.1'

services:
  node_application:
    container_name: node_application
    build:
      context: ./node_application
    image: co-code/node_application:latest
    environment:
      PORT: "81"
    volumes:
      - "./node_application:/workspace"
    networks:
      - service-network

  static:
    container_name: static
    build:
      context: ./static
    image: co-code/static:alpine
    environment:
      HOST: "node_application"
      PORT: "81"
    ports:
      - "127.0.0.1:80:80/tcp"
    volumes:
      - "./static/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./static/html:/usr/share/nginx/html"
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
